### ISSUE TITLE
The feed exists, the server is fine, and the problem is reproducible

### ISSUE THREAD

**Issue by sagarfeed** [w3c/feedvalidator#27] opened 2020-09-18 14:16 UTC
The feed exists, the server is fine, and the problem is reproducible. My feed not showing content in google news.
Url: https://www.mygenerationtechs.com/

**Comment by dontcallmedom** [comment] 2020-09-18 14:24
Can you say what error you're getting? When I try running it, I get a 503 error - is that what you're seeing?

If so, this seems linked to the Cloudflare Webapp firewall insisting on asking the validator to complete a captcha, which isn't going to happen…

**Comment by sagarfeed** [comment] 2020-09-18 14:26
Yes my website is on cloudflare

**Comment by SavvyTraveler** [comment] 2020-10-08 17:29
Hello,

My feed exists, the server is fine, and the problem is reproducible.

http://163.172.151.86/filmzone/filmzone/feed/feed.rss

**Comment by dontcallmedom** [comment] 2020-10-09 06:01
@SavvyTraveler this is because your feed exceeded the max size for the validator (which was set at 2MB); I've bumped it to 5MB, but in general, it's probably not ideal to have such a large feed for consumption by RSS readers.

Meanwhile closing this issue since the originally reported problem is not with the validator.

**Closed by dontcallmedom** 2020-10-09 06:01 UTC
