### ISSUE TITLE
Internal server not available

### ISSUE THREAD

**Issue by f-guerin** [w3c/feedvalidator#28] opened 2020-09-29 14:46 UTC
I'd like to add this adress in Thunderbird rss :
https://dcpoi.sos-data.fr/wiki/feed.php

But it appears unavailable.

**Comment by dontcallmedom** [comment] 2020-09-29 16:00
the problem is that the server TLS certificate is self-signed - this isn't realted to the feedvalidator, so closing the issue

**Closed by dontcallmedom** 2020-09-29 16:00 UTC
